DEFAULT_CATEGORIES = [
    {"id": "ceramics", "name": "Pottery & Ceramics", "image": "https://images.unsplash.com/photo-1631125915902-d8abe9225ff2?w=400"},
    {"id": "textiles", "name": "Textiles & Weaving", "image": "https://images.unsplash.com/photo-1544736779-15c123c4c66f?w=400"},
    {"id": "jewelry", "name": "Jewelry", "image": "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400"},
    {"id": "leather", "name": "Leather Goods", "image": "https://images.unsplash.com/photo-1628483211662-9bcc692c46dc?w=400"},
    {"id": "decor", "name": "Home Decor", "image": "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=400"},
    {"id": "art", "name": "Art & Prints", "image": "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=400"},
]


SEED_PRODUCTS = [
    {
        "title": "Hand-thrown Terracotta Vase",
        "description": "A quiet, sculptural vase thrown on a slow wheel in a small studio in Jaipur.\n\nEach vase carries the maker's fingerprints in the clay — no two are alike. Finished with a matte terracotta glaze that softens with time.",
        "price": 68.0,
        "category": "ceramics",
        "stock": 12,
        "materials": "Local red clay, matte glaze",
        "dimensions": "18cm × 12cm",
        "shipping_days": 7,
        "images": [
            "https://images.unsplash.com/photo-1631125915902-d8abe9225ff2?w=800",
            "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=800",
            "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=800",
        ],
        "tags": ["vase", "ceramic", "home decor"],
    },
    {
        "title": "Slow-stitched Leather Bifold",
        "description": "Cut from full-grain vegetable-tanned leather and saddle-stitched entirely by hand.\n\nA wallet designed to age quietly — the leather deepens with every day it lives in your pocket.",
        "price": 145.0,
        "category": "leather",
        "stock": 6,
        "materials": "Full-grain vegetable-tanned leather, waxed linen thread",
        "dimensions": "11cm × 9cm",
        "shipping_days": 10,
        "images": [
            "https://images.unsplash.com/photo-1628483211662-9bcc692c46dc?w=800",
            "https://images.unsplash.com/photo-1627123424574-724758594e93?w=800",
        ],
        "tags": ["wallet", "leather", "edc"],
    },
    {
        "title": "Handwoven Wool Throw",
        "description": "Woven on a floor loom from undyed Merino wool.\n\nWarm without being heavy, this throw takes about three days on the loom and finishes on a wooden beam. A quiet, useful object.",
        "price": 210.0,
        "category": "textiles",
        "stock": 4,
        "materials": "100% undyed Merino wool",
        "dimensions": "180cm × 130cm",
        "shipping_days": 12,
        "images": [
            "https://images.unsplash.com/photo-1544736779-15c123c4c66f?w=800",
            "https://images.unsplash.com/photo-1615529182904-14819c35db37?w=800",
        ],
        "tags": ["throw", "wool", "textile"],
    },
    {
        "title": "Brass Crescent Earrings",
        "description": "Hammered from a single sheet of raw brass and finished by hand.\n\nLight to wear, warm in tone, and designed to develop a soft patina over the years.",
        "price": 42.0,
        "category": "jewelry",
        "stock": 20,
        "materials": "Raw brass, sterling silver posts",
        "dimensions": "3cm drop",
        "shipping_days": 5,
        "images": [
            "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800",
            "https://images.unsplash.com/photo-1602752250015-52934bc45613?w=800",
        ],
        "tags": ["earrings", "brass", "jewelry"],
    },
    {
        "title": "Carved Olive Wood Bowl",
        "description": "Turned from a single piece of storm-fallen olive wood.\n\nThe grain — never the same twice — is the whole point. Finished with food-safe walnut oil.",
        "price": 88.0,
        "category": "decor",
        "stock": 9,
        "materials": "Olive wood, walnut oil",
        "dimensions": "22cm diameter",
        "shipping_days": 8,
        "images": [
            "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800",
            "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=800",
        ],
        "tags": ["bowl", "wood", "kitchen"],
    },
    {
        "title": "Botanical Monoprint — Fern",
        "description": "A single-run monoprint pressed from a real fern leaf onto handmade cotton paper.\n\nEach print is unique and signed by the artist. Ships flat, unframed.",
        "price": 55.0,
        "category": "art",
        "stock": 15,
        "materials": "Water-based ink, handmade cotton paper",
        "dimensions": "A4 / 21cm × 30cm",
        "shipping_days": 6,
        "images": [
            "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800",
            "https://images.unsplash.com/photo-1502085671122-2d218cd434e6?w=800",
        ],
        "tags": ["print", "botanical", "art"],
    },
]
