export const theme = {
  color: {
    surface: '#FAF9F6',
    onSurface: '#1A1A1A',
    surfaceSecondary: '#FFFFFF',
    surfaceTertiary: '#F0EBE1',
    onSurfaceTertiary: '#4A453E',
    surfaceInverse: '#2B2927',
    onSurfaceInverse: '#FAF9F6',
    brand: '#B56A56',
    brandPrimary: '#B56A56',
    onBrandPrimary: '#FFFFFF',
    brandSecondary: '#D89E8A',
    brandTertiary: '#F4E3DD',
    onBrandTertiary: '#7A3E2E',
    success: '#6B8E6B',
    onSuccess: '#FFFFFF',
    warning: '#D4A373',
    onWarning: '#2B2927',
    error: '#A85A5A',
    onError: '#FFFFFF',
    info: '#8C867B',
    onInfo: '#FFFFFF',
    onSurfaceSecondary: '#1A1A1A',
    border: '#E6E1D8',
    borderStrong: '#CCC4B8',
    divider: '#F0EBE1',
    // Intentional alias of `info` — kept as a separate semantic name since it's
    // used widely for secondary/placeholder text, distinct from info-badge usage.
    muted: '#8C867B',
  },
  spacing: { xs: 4, sm: 8, md: 12, lg: 16, xl: 24, xxl: 32, xxxl: 48, xxxxl: 64, gutter: 80 },
  radius: { sm: 6, md: 12, lg: 20, pill: 999 },
  breakpoints: { tablet: 768, desktop: 1024 },
  containerMaxWidth: { tablet: 900, desktop: 1280 },
  font: {
    heading: 'PlayfairDisplay_500Medium',
    body: 'DMSans_400Regular',
    bodyMedium: 'DMSans_500Medium',
  },
  text: {
    sm: 12,
    base: 14,
    lg: 16,
    xl: 20,
    xxl: 24,
    display: 32,
    hero: 44,
  },
  elevation: {
    subtle: {
      shadowColor: '#2B2927',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 12,
      elevation: 2,
    },
    lift: {
      shadowColor: '#2B2927',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.1,
      shadowRadius: 20,
      elevation: 4,
    },
  },
};
